#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR"/shell_axerish.dex

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX, please check the tutorial in AxManager app"
  exit 1
fi

if [ "$(getprop ro.build.version.sdk)" -ge 34 ]; then
  if [ -w "$DEX" ]; then
    echo "On Android 14+, app_process cannot load writable dex."
    echo "Attempting to remove the write permission..."
    chmod 400 "$DEX"
  fi
  if [ -w "$DEX" ]; then
    echo "Cannot remove the write permission of $DEX."
    echo "You can copy the file to terminal app's private directory (/data/data/<package>)"
    exit 1
  fi
fi

if [ -z "$APPLICATION_ID" ]; then
  APPLICATION_ID=$(echo "$BASEDIR" | sed -n 's#.*/data/data/\([^/]*\)/.*#\1#p')
  export APPLICATION_ID
fi

/system/bin/app_process \
  -Djava.class.path="$DEX" \
  /system/bin \
  --nice-name=axerish \
  frb.axeron.ShellLoader "$@"
